title: boating
description: Boating and Sailing Documentation - AI assisted
remote_theme: just-the-docs/just-the-docs
color_scheme: blue
plugins:
  - jekyll-seo-tag

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red